import type { Offer } from "./types.js";

/** Organic comparison catalog. tosCashbackOk is false until a program explicitly allows rebate. */
export const OFFERS: Offer[] = [
  {
    id: "clerk",
    name: "Clerk",
    category: "auth",
    url: "https://clerk.com",
    pricing: "Free tier; Pro from ~$25/mo",
    lockIn: "Medium — hosted user model, React-first components",
    stackTags: ["javascript", "typescript", "nextjs", "react", "remix"],
    regions: ["us", "eu"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: "https://clerk.com/creators",
    affiliateUrl: null,
    commissionNotes: "Creator sponsorships, not a public CPA program.",
  },
  {
    id: "auth0",
    name: "Auth0",
    category: "auth",
    url: "https://auth0.com",
    pricing: "Free essentials; paid by MAU",
    lockIn: "High — enterprise IdP, custom domains on paid plans",
    stackTags: ["javascript", "python", "java", "go", "nextjs"],
    regions: ["us", "eu", "au"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: "https://auth0.com/partners",
    affiliateUrl: null,
    commissionNotes: "Partner program, not cookie CPA.",
  },
  {
    id: "supabase-auth",
    name: "Supabase Auth",
    category: "auth",
    url: "https://supabase.com/auth",
    pricing: "Included with Supabase Free/Pro",
    lockIn: "Medium — strongest when you already use Supabase Postgres",
    stackTags: ["javascript", "typescript", "python", "nextjs", "flutter"],
    regions: ["us", "eu", "ap"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: "https://supabase.com/partners",
    affiliateUrl: null,
    commissionNotes: "No public affiliate; marketplace is integrations.",
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "db",
    url: "https://supabase.com",
    pricing: "Free; Pro from $25/mo",
    lockIn: "Medium — Postgres is portable; Auth/Storage/Realtime are stickier",
    stackTags: ["javascript", "typescript", "python", "nextjs", "postgres"],
    regions: ["us", "eu", "ap"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: "https://supabase.com/partners",
    affiliateUrl: null,
    commissionNotes: "No public CPA.",
  },
  {
    id: "neon",
    name: "Neon",
    category: "db",
    url: "https://neon.tech",
    pricing: "Free; Launch/Scale paid",
    lockIn: "Low-medium — standard Postgres; branching is the hook",
    stackTags: ["javascript", "typescript", "python", "postgres", "nextjs"],
    regions: ["us", "eu"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: null,
    affiliateUrl: null,
    commissionNotes: "GitHub Sponsors OSS referral only, not a general affiliate.",
  },
  {
    id: "planetscale",
    name: "PlanetScale",
    category: "db",
    url: "https://planetscale.com",
    pricing: "Hobby free; Scaler paid",
    lockIn: "Medium — Vitess/MySQL; branching workflows",
    stackTags: ["javascript", "typescript", "php", "mysql", "prisma"],
    regions: ["us", "eu"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: null,
    affiliateUrl: null,
    commissionNotes: "Prior affiliate join URL appears discontinued.",
  },
  {
    id: "railway",
    name: "Railway",
    category: "hosting",
    url: "https://railway.com",
    pricing: "Usage-based; Hobby/Pro",
    lockIn: "Medium — easy deploys; data on their volumes",
    stackTags: ["javascript", "typescript", "python", "go", "docker", "nextjs"],
    regions: ["us", "eu"],
    hasPublicCpa: true,
    tosCashbackOk: false,
    network: "railway",
    signupUrl: "https://railway.com/affiliate-program",
    affiliateUrl: null,
    commissionNotes:
      "First-party refer: 15% of invoices for 12 months. Instant link from dashboard. Rebate off until TOS reviewed.",
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    category: "hosting",
    url: "https://www.digitalocean.com",
    pricing: "Droplets from ~$4–$6/mo; App Platform paid",
    lockIn: "Low-medium — VMs/K8s are portable",
    stackTags: ["docker", "python", "go", "javascript", "linux"],
    regions: ["us", "eu", "ap"],
    hasPublicCpa: true,
    tosCashbackOk: false,
    network: "cj",
    signupUrl: "https://www.digitalocean.com/affiliates",
    affiliateUrl: null,
    commissionNotes:
      "CJ Affiliate: ~10% of spend for 12 months. Apply as publisher. Cashback likely restricted.",
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "hosting",
    url: "https://vercel.com",
    pricing: "Hobby free; Pro $20/user/mo",
    lockIn: "High for Next.js frontend; serverless + edge",
    stackTags: ["javascript", "typescript", "nextjs", "react"],
    regions: ["us", "eu"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: "https://vercel.com/partners",
    affiliateUrl: null,
    commissionNotes:
      "No consumer hosting CPA. v0 is a separate Dub program that bans coupon aggregators and benefiting a third party.",
  },
  {
    id: "resend",
    name: "Resend",
    category: "email",
    url: "https://resend.com",
    pricing: "Free 3k emails; Pro from $20/mo",
    lockIn: "Low-medium — transactional API, React Email",
    stackTags: ["javascript", "typescript", "nextjs", "react"],
    regions: ["us"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: null,
    affiliateUrl: null,
    commissionNotes: "No public affiliate program found.",
  },
  {
    id: "postmark",
    name: "Postmark",
    category: "email",
    url: "https://postmarkapp.com",
    pricing: "Paid from a small monthly; no typical free prod tier",
    lockIn: "Low — SMTP/API, excellent deliverability niche",
    stackTags: ["javascript", "python", "ruby", "php"],
    regions: ["us", "eu"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: null,
    affiliateUrl: null,
    commissionNotes: "Check current partner page before assuming CPA.",
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    category: "email",
    url: "https://sendgrid.com",
    pricing: "Free 60 days then Essentials paid",
    lockIn: "Medium — Twilio ecosystem",
    stackTags: ["javascript", "python", "php", "java"],
    regions: ["us", "eu"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: "https://sendgrid.com/en-us/partners/become",
    affiliateUrl: null,
    commissionNotes: "Twilio partner track, not a standard affiliate cookie.",
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "payments",
    url: "https://stripe.com",
    pricing: "2.9% + 30¢ typical US cards; no monthly for basic",
    lockIn: "High — billing, Connect, Radar",
    stackTags: ["javascript", "python", "ruby", "php", "nextjs"],
    regions: ["us", "eu", "ap"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: "https://stripe.com/partners/become-a-partner",
    affiliateUrl: null,
    commissionNotes: "Partner ecosystem, not public CPA.",
  },
  {
    id: "lemonsqueezy",
    name: "Lemon Squeezy",
    category: "payments",
    url: "https://www.lemonsqueezy.com",
    pricing: "5% + 50¢ MoR; Merchant of Record",
    lockIn: "Medium — MoR tax handling",
    stackTags: ["javascript", "typescript", "nextjs"],
    regions: ["us", "eu"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: null,
    affiliateUrl: null,
    commissionNotes: "Affiliate exists historically; confirm TOS before rebate.",
  },
  {
    id: "paddle",
    name: "Paddle",
    category: "payments",
    url: "https://www.paddle.com",
    pricing: "MoR percentage + fee",
    lockIn: "Medium-high — MoR + catalog",
    stackTags: ["javascript", "php", "python"],
    regions: ["us", "eu"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: null,
    affiliateUrl: null,
    commissionNotes: "Classic software affiliate possible; not auto-enrolled.",
  },
  {
    id: "posthog",
    name: "PostHog",
    category: "observability",
    url: "https://posthog.com",
    pricing: "Generous free; usage paid",
    lockIn: "Medium — product analytics + session replay",
    stackTags: ["javascript", "python", "nextjs", "react"],
    regions: ["us", "eu"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "in-house",
    signupUrl: "https://posthog.com/partnerships",
    affiliateUrl: null,
    commissionNotes: "Selective partnership form, not an open catalog CPA.",
  },
  {
    id: "datadog",
    name: "Datadog",
    category: "observability",
    url: "https://www.datadoghq.com",
    pricing: "Per-host / per-GB; expensive at scale",
    lockIn: "High — APM + logs + infra",
    stackTags: ["python", "go", "java", "javascript", "kubernetes"],
    regions: ["us", "eu"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: null,
    affiliateUrl: null,
    commissionNotes: "Enterprise partners, not IC cookie CPA.",
  },
  {
    id: "grafana-cloud",
    name: "Grafana Cloud",
    category: "observability",
    url: "https://grafana.com/products/cloud",
    pricing: "Free k6/metrics tier; usage paid",
    lockIn: "Low-medium — Prometheus/Loki portable",
    stackTags: ["go", "python", "kubernetes", "prometheus"],
    regions: ["us", "eu"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: null,
    affiliateUrl: null,
    commissionNotes: "No Shortlist CPA in MVP.",
  },
  {
    id: "sentry",
    name: "Sentry",
    category: "errors",
    url: "https://sentry.io",
    pricing: "Free developer; Team paid",
    lockIn: "Medium — SDK in every service",
    stackTags: ["javascript", "python", "ruby", "go", "java", "nextjs"],
    regions: ["us", "eu"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "in-house",
    signupUrl: "https://sentry.io/partners",
    affiliateUrl: null,
    commissionNotes: "Partnership page; not a reliable public CPA.",
  },
  {
    id: "bugsnag",
    name: "Bugsnag",
    category: "errors",
    url: "https://www.bugsnag.com",
    pricing: "Paid plans by events",
    lockIn: "Medium",
    stackTags: ["javascript", "ruby", "python", "java", "php"],
    regions: ["us", "eu"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: null,
    affiliateUrl: null,
    commissionNotes: "Organic comparison only.",
  },
  {
    id: "rollbar",
    name: "Rollbar",
    category: "errors",
    url: "https://rollbar.com",
    pricing: "Free small; paid by events",
    lockIn: "Medium",
    stackTags: ["javascript", "python", "ruby", "php"],
    regions: ["us"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: null,
    affiliateUrl: null,
    commissionNotes: "Organic comparison only.",
  },
  {
    id: "launchdarkly",
    name: "LaunchDarkly",
    category: "feature-flags",
    url: "https://launchdarkly.com",
    pricing: "Enterprise-leaning paid",
    lockIn: "High — flags in every service",
    stackTags: ["javascript", "java", "go", "python", "react"],
    regions: ["us", "eu"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: "https://launchdarkly.com/partner-program",
    affiliateUrl: null,
    commissionNotes: "Tech partner, not CPA.",
  },
  {
    id: "statsig",
    name: "Statsig",
    category: "feature-flags",
    url: "https://www.statsig.com",
    pricing: "Generous free; usage paid",
    lockIn: "Medium — flags + experiments",
    stackTags: ["javascript", "python", "react", "nextjs"],
    regions: ["us"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: null,
    affiliateUrl: null,
    commissionNotes: "Organic comparison only.",
  },
  {
    id: "unleash",
    name: "Unleash",
    category: "feature-flags",
    url: "https://www.getunleash.io",
    pricing: "OSS self-host free; Unleash Cloud paid",
    lockIn: "Low if self-hosted OSS",
    stackTags: ["javascript", "java", "go", "python", "docker"],
    regions: ["us", "eu"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: null,
    affiliateUrl: null,
    commissionNotes: "Organic comparison only.",
  },
  {
    id: "inngest",
    name: "Inngest",
    category: "queues",
    url: "https://www.inngest.com",
    pricing: "Free; paid by executions",
    lockIn: "Medium — function SDK",
    stackTags: ["javascript", "typescript", "nextjs", "python"],
    regions: ["us"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: null,
    affiliateUrl: null,
    commissionNotes: "Organic comparison only.",
  },
  {
    id: "triggerdev",
    name: "Trigger.dev",
    category: "queues",
    url: "https://trigger.dev",
    pricing: "Free; paid by runs",
    lockIn: "Medium — background jobs SDK",
    stackTags: ["javascript", "typescript", "nextjs"],
    regions: ["us", "eu"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: null,
    affiliateUrl: null,
    commissionNotes: "Organic comparison only.",
  },
  {
    id: "upstash-qstash",
    name: "Upstash QStash",
    category: "queues",
    url: "https://upstash.com/qstash",
    pricing: "Pay-as-you-go",
    lockIn: "Low-medium — HTTP jobs",
    stackTags: ["javascript", "typescript", "python", "nextjs"],
    regions: ["us", "eu"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: null,
    affiliateUrl: null,
    commissionNotes: "No public affiliate found.",
  },
  {
    id: "cloudflare-r2",
    name: "Cloudflare R2",
    category: "storage",
    url: "https://www.cloudflare.com/developer-platform/r2/",
    pricing: "No egress fees; storage/class A/B ops",
    lockIn: "Low — S3-compatible API",
    stackTags: ["javascript", "typescript", "python", "go", "workers"],
    regions: ["global"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: "https://portal.cloudflarepartners.com",
    affiliateUrl: null,
    commissionNotes: "Channel partners, not consumer affiliate.",
  },
  {
    id: "aws-s3",
    name: "Amazon S3",
    category: "storage",
    url: "https://aws.amazon.com/s3/",
    pricing: "Pay-as-you-go storage + request + egress",
    lockIn: "Low API, high account gravity",
    stackTags: ["python", "java", "go", "javascript", "terraform"],
    regions: ["global"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: "https://aws.amazon.com/partners",
    affiliateUrl: null,
    commissionNotes: "APN, not Amazon Associates for AWS.",
  },
  {
    id: "uploadthing",
    name: "UploadThing",
    category: "storage",
    url: "https://uploadthing.com",
    pricing: "Free; paid by storage/bandwidth",
    lockIn: "Medium — Next.js helper DX",
    stackTags: ["javascript", "typescript", "nextjs", "react"],
    regions: ["us"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: null,
    affiliateUrl: null,
    commissionNotes: "Organic comparison only.",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    category: "llm-router",
    url: "https://openrouter.ai",
    pricing: "Pass-through model prices + small fee",
    lockIn: "Low — OpenAI-compatible API",
    stackTags: ["javascript", "python", "typescript"],
    regions: ["us"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: null,
    affiliateUrl: null,
    commissionNotes: "Organic comparison only. OpenAI/Anthropic have no public CPA.",
  },
  {
    id: "helicone",
    name: "Helicone",
    category: "llm-router",
    url: "https://www.helicone.ai",
    pricing: "Free; paid observability",
    lockIn: "Low-medium — proxy/gateway",
    stackTags: ["javascript", "python", "typescript"],
    regions: ["us", "eu"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: null,
    affiliateUrl: null,
    commissionNotes: "Organic comparison only.",
  },
  {
    id: "portkey",
    name: "Portkey",
    category: "llm-router",
    url: "https://portkey.ai",
    pricing: "Gateway free tier; paid control plane",
    lockIn: "Medium — routing + guardrails",
    stackTags: ["javascript", "python", "typescript"],
    regions: ["us"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: null,
    affiliateUrl: null,
    commissionNotes: "Organic comparison only.",
  },
  {
    id: "pinecone",
    name: "Pinecone",
    category: "vector",
    url: "https://www.pinecone.io",
    pricing: "Free starter; paid by usage",
    lockIn: "Medium-high — proprietary index",
    stackTags: ["python", "javascript", "typescript"],
    regions: ["us", "eu"],
    hasPublicCpa: true,
    tosCashbackOk: false,
    network: "partnerstack",
    signupUrl: "https://market.partnerstack.com/page/pinecone",
    affiliateUrl: null,
    commissionNotes:
      "PartnerStack: ~10% of first year, $1,200 cap. Network + vendor approval. Rebate off by default.",
  },
  {
    id: "qdrant-cloud",
    name: "Qdrant Cloud",
    category: "vector",
    url: "https://qdrant.tech/cloud/",
    pricing: "OSS self-host; Cloud paid clusters",
    lockIn: "Low if self-host OSS",
    stackTags: ["python", "javascript", "rust", "docker"],
    regions: ["us", "eu"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: null,
    affiliateUrl: null,
    commissionNotes: "Organic comparison only.",
  },
  {
    id: "weaviate-cloud",
    name: "Weaviate Cloud",
    category: "vector",
    url: "https://weaviate.io/hybrid-search",
    pricing: "OSS + WCD paid",
    lockIn: "Medium",
    stackTags: ["python", "javascript", "go"],
    regions: ["us", "eu"],
    hasPublicCpa: false,
    tosCashbackOk: false,
    network: "none",
    signupUrl: null,
    affiliateUrl: null,
    commissionNotes: "Organic comparison only.",
  },
];
